### ISSUE TITLE
Demo not working in simulator

### ISSUE THREAD

**Issue by sylzys** [BelinChung/HiApp#11]
你好,

I've been looking at your app HiApp on github, really helped me getting familiar with framework7.
![Uploading Capture d’écran 2015-10-06 à 15.39.30.png…]()

I've been running `gulp build`, but I still don't get any content (besides navbar and tabbar) when I launch the app in the iOS simulator. Same goes if I use `cordova build ios`

Everything goes well when i launch `gulp build-dev` and use webpack-server in a browser.
Am I missing something here ? :(
谢谢你！
![hiapp](https://cloud.githubusercontent.com/assets/1545358/10310114/85d8d4ac-6c40-11e5-9e83-9138b89101be.png)

**Comment by sylzys** [comment]
App is not working neither when I use local webserver instead of webpack-server :(

**Comment by BelinChung** [comment]
Hi, Can you provide some debugging information from Console.
Maybe you can use [GapDebug](https://www.genuitec.com/products/gapdebug/) to get the debugging information from iOS simulator as Chrome Console. :)

**Comment by sylzys** [comment]
谢谢你快回答：）
Unfortunately, GapDebug console shows no error :/
![capture d ecran 2015-10-08 a 10 59 25](https://cloud.githubusercontent.com/assets/1545358/10361971/d785cd8e-6dab-11e5-93d3-f9b752f1d776.png)

The ressource tab seems to be ok:
![capture d ecran 2015-10-08 a 11 01 10](https://cloud.githubusercontent.com/assets/1545358/10362002/f2e2b312-6dab-11e5-9098-fdbd9a2e915f.png)

**Comment by sylzys** [comment]
对了，用Genymotion也不工作 :(
![capture d ecran 2015-10-08 a 11 54 29](https://cloud.githubusercontent.com/assets/1545358/10363209/8941d2fa-6db3-11e5-965a-bac28e89e729.png)

But here I have some errors in console :
![capture d ecran 2015-10-08 a 11 55 08](https://cloud.githubusercontent.com/assets/1545358/10363218/9507a484-6db3-11e5-8d8a-725676a78d3a.png)

**Comment by BelinChung** [comment]
Hi, Maybe I can find some bug from compiled files, please pack it, and upload here.

**Comment by sylzys** [comment]
Here is the www folder : http://jingleweb.fr/tmp/HiAppWWW.tgz
Thanks !

**Comment by sylzys** [comment]
The "unknown property 'type' of undefined "error" came from the fact that I didn't have `cordova-plugin-network-information` plugin installed, so using a device or a simulator, `navigator.connection`did not exist (var used in networkStatus.js l.4)

That being said, I think there are a few problems in the gulp/webpack config, because some files are not copied, some are removed... 
I created a task "copy" where I moved every fse.copySync requests, and run it before build-dev. After that, cordova run is working :+1: 
Thanks for your good work !

**Comment by BelinChung** [comment]
I am so sorry, this is the first time I have used `webpack` to build a project.
[FIS](https://github.com/BelinChung/HiApp/tree/fis3) is very popular in China, I am more familiar with it.
But unfortunately, It is missing English document.
Maybe I should spend more time to learn `webpack`. : )

**Comment by sylzys** [comment]
嘿，没问题！
你的APP很好，帮了我很多 ：）
如果我用Webpack有进步，我告诉你：）

谢谢！

**Comment by BelinChung** [comment]
Closing (inactivity)
