### ISSUE TITLE
请问mian.js的23行为什么用 app.receivedEvent('deviceready'); 而不用 this.receivedEvent('deviceready');

### ISSUE THREAD

**Issue by WangHaoming** [BelinChung/HiApp#13]
我调试了一下 app在这里完全等于this。这种写法有什么特殊的意义吗？

**Comment by BelinChung** [comment]
没，它们是等价的，因为某个时间段，该方法内的 `this` 不是指向 `app`，所以用 `app.receivedEvent('deviceready');` ,但是后来代码重构，`this` 指向回了 `app`，但是对应的代码没有跟着改回来而已。

**Comment by WangHaoming** [comment]
谢谢你的回答。这个hiapp的代码写的很干净。我准备基于这个代码做一个小的app可以吗？

**Comment by BelinChung** [comment]
MIT licensed
随意用

**Comment by baidansir** [comment]
感谢！

**Comment by BelinChung** [comment]
Closing (inactivity)
