### ISSUE TITLE
win7下怎么打包啊？

### ISSUE THREAD

**Issue by gpsim** [BelinChung/HiApp#14]
能详细点吗？大神，不会用webpack 谢谢

**Comment by NexusLee** [comment]
ios 都改成Android，只能编译Android

**Comment by BelinChung** [comment]
具体编译教程可查：Android iOS 编译 打包 等关键字
只要记住：cordova 生成的是标准的 iOS Android 工程，他们怎么编译原生APP，这个项目就怎么编译。
