### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by jiashaoying** [BelinChung/HiApp#23]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HiApp@3.1.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the HiApp@3.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BelinChung** [comment]
fixed
