### ISSUE TITLE
false

### ISSUE THREAD

**Issue by wozzup** [BelinChung/HiApp#7]
false

**Comment by BelinChung** [comment]
Hi
在很前期的时候，F7 是还没有 Template7 的，所以 HiApp 使用了 Mustache.js ，后来有了 Template7 ，自然选用了内置的 Template7 ，不过他们的语法是相同的。
不过还是要说一下 HiApp 只是 Demo，你不应该在这个基础上改成自己的 APP，require text 当然也不是必要的，你可以选择自己喜欢的模板加载方式。

**Comment by wozzup** [comment]
hi 明白了。
我是想做一个多语言的 rss 订阅阅读器。。。所以参考了你的 hiapp 

因为我看到 Template7 不用 require text 也可以加载模版啊，所以就问问为什么需要用到 require text 是因为多语言还是模版加载呢？

**Comment by wozzup** [comment]
然后，我看到 ```tplManager.js``` 文件有一个 ```renderRemoteTpl``` 方法，看起来是一个自动编译模板的方法，但是这个方法好像没有在任何在方调用过。

```
        renderRemoteTpl: function(tplName,renderData,callback){
            tplName = tplName || '';
            $$.get('page/' + tplName + '.tpl.html' ,function(markup){
                var compiledTemplate = t7.compile(markup);
                var output = compiledTemplate(renderData);

                typeof(callback === 'function') ? callback(output) : null;
            });

        },
```

当前我遇到自动编译模板的问题。。。能帮忙看看吗？
比如，有一个 contacts.html 模板文件要自动编译：

初始化 my-app.js：
```
var myApp = new Framework7({
    precompileTemplates: true,
    template7Pages: true
});
var mainView = myApp.addView('.view-main');
```
index.html
```
......
<a href='contacts.html'>Contacts</a>
......
```
模版文件 contacts.html
```
<script id="contactsTemplate" type="text/template7">
  <div class="page" data-page="contacts">
    <div class="page-content">
        <p>You can contact me:</p>
        <p>By phone: {{tel}}</p>
        <p>By email: {{email}}</p>
    </div>
  </div>
</script>
```

这样做，好像没有自动编译 contacts.html 文件：
```
mainView.router.load({
    url: 'contacts.html',
    context: {
      tel: '(999)-111-22-33',
      email: 'contact@john.doe'
    }
})
```

**Comment by BelinChung** [comment]
尝试下这样？
```
var contactsHtml = Template7.templates.contactsTemplate({
      tel: '(999)-111-22-33',
      email: 'contact@john.doe'
});
mainView.router. loadContent(contactsHtml);
```
你给的一部分代码也很难确定问题所在，建议你断点，一步一步跟，看哪里出问题了。

**Comment by wozzup** [comment]
谢啦！
还有一个问题：

https://dearb.me/hi/build/

这个部分登录 sign in 页面，我弄了一下午＋一晚上了，一直都是先显示默认的 view page 然后，经过 js 判断后才显示登录页面，有没有什么办法，让他：

js 先判断：
如果有登录，显示列表
如果没有登录，显示登录

最重要的是，不要让他显示滑动一下（去掉从右边滑入的动画之后，他还是会闪一下），
也就是说动态修改启动页面，页面无闪动无动画。

**Comment by wozzup** [comment]
我在 router.js 里边这样写了：

```
var router = {

    init: function() {
        // 检查授权
        mainView.router.loadPage({
            url: 'page/login.html',
            animatePages: false,
            reload: true,
            force: true
        });
    },

    ...
}
```

去掉动画，页面还是会闪动一下，因为无论怎么做，webview 首先加载的是 index.html 里边的 body
去掉所有 </body> 里边的内容，只留下 requirejs 页面还是会先显示一下空白，而不是直接显示 login.html 
。。。头大。。。求帮助

**Comment by wozzup** [comment]
我现在暂时是用一个 loading... 页面替代的，大神有空帮忙看看。先谢谢啦
