### ISSUE TITLE
怎么登陆功能不能用啦？

### ISSUE THREAD

**Issue by dfktv** [BelinChung/HiApp#9]
你好，看了几个不同的DEMO，感觉你的这个做的很好，最近又看到了你的更新，但是那个登陆功能怎么没有了，是还没做完，还是什么其他原因呢。希望你能继续更新，谢谢

**Comment by BelinChung** [comment]
Hi，项目还是更希望展现不同构建工具的项目实践和模块化、组件化的思想，可能一些 UI 展现上会稍微欠缺一点。

**Comment by BelinChung** [comment]
Closing (inactivity)
